version: '2'
services:
    component-app:
        image: component
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://component-mysql:3306/component?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    component-mysql:
        extends:
            file: mysql.yml
            service: component-mysql
